------
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidylog)
library(data.table)
library(ggforce)
library(ggstatsplot)
```


```{r}

Clinical <- read.csv("clinical_na_rm.csv") %>%
 separate(X, c("Study", "ID"), "-") %>%
  mutate(CSV = "Clinical") %>%
  mutate(missing = rowSums(is.na(.))) %>%
  mutate(across(!c(Study, CSV), as.numeric))%>%
  mutate(Multimorbidity = rowSums(select(., HEENT:Depression),na.rm = TRUE))

Clinical$ID <- as.numeric(Clinical$ID)
  
Montoya <- read.csv("montoyaFIN_GE_coVars.csv") %>%
  rename(ID = xID) %>%
  mutate(CSV = "Montoya") %>%
  mutate(missing = rowSums(is.na(.))) %>%
  mutate(Study = "CFS")

Montoya$ID <- as.numeric(Montoya$ID)

Stanford <- read.csv("stanford_1kip.csv") %>%
  separate(xID, c("Study", "ID"), "_") %>%
  mutate(CSV = "Stanford") %>%
  mutate(missing = rowSums(is.na(.)))

Stanford$ID <- as.numeric(Stanford$ID)


table(Stanford$GENDER)
#See <- Stanford %>%
#  mutate(Strange = ifelse(CD4_45RApos_S1_IFNA == max(FinalDataset$CD4_45RApos_S1_IFNA) #, "Yes", ifelse(CD8_S1_IL10 == max(FinalDataset$CD8_S1_IL10), "Extreme Outlier", #"No"))) #same 72

#not many missing. Focus on clinical and rest now 
```


```{r}
#PCA - go back to repeated measuremnts. Can we see a patetrn of individuals? 
library(factoextra)
library(FactoMineR)
library(FactoInvestigate)
  #https://aedin.github.io/PCAworkshop/articles/b_PCA.html

set.seed(132)

Dataset <- Stanford %>% select_if(is.numeric) %>% select(-c(ID, missing))

Facto <- PCA(Dataset,  quali.sup = c(3,4), scale.unit = TRUE, ncp = 2, graph = TRUE) #maybe difference has to do with gender?

fviz_eig(Facto, addlabels = TRUE, ylim = c(0, 50))

#Facto <- PCA(Dataset %>% select(unique(Select$name)), scale.unit = TRUE, ncp = 10, graph = TRUE) #maybe difference has to do with gender? # very little variancee explained

```

```{r}

FinalDataHMMatrix <- data.frame(Facto[["var"]][["coord"]]) %>%
  as.matrix()

library(pheatmap)
class(FinalDataHMMatrix) <- "numeric"

pdf("Heatmap.pdf", 5, 18)
print(pheatmap(FinalDataHMMatrix,border_color = "black",fontsize_col = 6,  fontsize_row = 6, cluster_cols  = FALSE))
dev.off()


library(ComplexHeatmap)

pdf("Heatmap2.pdf", 5,18)
HM <- (Heatmap(FinalDataHMMatrix, name = "Correlation", k = 4, row_names_gp = gpar(fontsize = 7), column_names_gp = gpar(fontsize = 7), border = "black", cluster_columns=FALSE))
print(HM)
dev.off()

Facto20 <- PCA(Dataset,  quali.sup = c(3,4), scale.unit = TRUE, ncp = 20, graph = TRUE) #maybe difference has to do with gender?
FinalDataHMMatrix20 <- data.frame(Facto20[["var"]][["coord"]]) %>%
  as.matrix()

pdf("Heatmap20.pdf", 5,18)
HM <- (Heatmap(FinalDataHMMatrix20, name = "Correlation", k = 4, row_names_gp = gpar(fontsize = 7), column_names_gp = gpar(fontsize = 7), border = "black", cluster_columns=FALSE))
print(HM)
dev.off()


####### Extract clusters 

HM_info <- draw(HM)
List <- row_order(HM_info)

clu_df <- lapply(names(List), function(i){
  out <- data.frame(Features = HM@row_names_param[["labels"]][List[[i]]],
                                             Cluster = paste0("cluster", i),
                                             stringsAsFactors = FALSE)
     return(out)
   }) %>%  
     do.call(rbind, .)





```

```{r}
Individuals <- classif(Facto20, file = "", nclust = -1, selec = "contrib", coef = 1, 
         figure.title = "Figure", graph = TRUE, options = NULL)

Ind_clus <- data.frame(Individuals$data.clust) %>%
  add_rownames() %>%
  select(clust, rowname)

PlotInd <- Dataset %>%
  add_column(Ind_clus) %>%
  pivot_longer(-c(clust, rowname))

PlotInd1 <- PlotInd %>%
  group_by(clust,name) %>%
  summarise(mean=mean(value), sd=sd(value)) %>%
  select(-rowname)

PlotInd2 <-PlotInd %>%
  ungroup() %>%
  group_by(name) %>%
  summarise(mean=mean(value), sd=sd(value)) %>%
  add_column(clust = "Mean")

PlotIndFinal <- rbind(PlotInd1, PlotInd2)
  
p <- ggplot(PlotIndFinal, aes(clust, mean, colour = clust)) + geom_point(position = "dodge")  + geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9))+theme_bw() + facet_wrap_paginate(name ~. , scales = "free", ncol = 7, nrow = 7) 

pdf("MeanClusterMine.pdf",15,10)
for(i in 1:n_pages(p)){
  p_save <-  p + 
    facet_wrap_paginate(name ~ .,scales = "free", ncol = 7, nrow = 7, page = i)
  print(p_save)
}

dev.off()


HMIndividual <- PlotIndFinal %>%
  select(-sd) %>%
  pivot_wider(names_from = clust, values_from = mean ) 


FinalDataHMMatrix <- data.frame(HMIndividual) %>%
    select(-name) %>%
  mutate_at(vars(starts_with('X')), ~ . /Mean) %>% #normlaize with respetc to mean change
  mutate_at(vars(starts_with('X')), ~ log(.)) %>% #normlaize with respetc to mean change
  select(-Mean) %>%
  as.matrix()

rownames(FinalDataHMMatrix) <- HMIndividual$name

library(pheatmap)
class(FinalDataHMMatrix) <- "numeric"
colnames(FinalDataHMMatrix) <- c("Clust.1", "Clust.2", "Clust.3")
#scale with repsect to the mean ( also plot points with respect to the mean)

#extract PCA scores and create decision tree - predict BMI


pdf("HeatmapInd.pdf", 5, 18)
print(pheatmap(FinalDataHMMatrix,border_color = "black",fontsize_col = 6,  fontsize_row = 6, cluster_cols  = FALSE))
dev.off()


```
#Genes and Diseases 


```{r}
#Genes

Genes <- Stanford %>%
  add_column(Ind_clus) %>%
  filter(Study == "CFS") %>%
  select(clust,ID) %>%
  inner_join(Montoya %>% select(-c(CSV, Study, missing, CMV:bmi_montoya...1.)) %>%
               rename(IL1BGene = "IL1B", IL8Gene = "IL8", TGFAGene = "TGFA")) %>%
  select(-ID)


res2 <- 
  tbl_df(Genes)%>% 
  pivot_longer(cols = -clust, names_to = "Features", values_to = "value") 
A <- filter(res2, Features == "AARS2") %>%
  drop_na()

#summary(aov(value ~ clust, data = A))[[1]][["Pr(>F)"]][1]
#pairwise.wilcox.test(A$value,as.factor(A$clust),p.adjust.method = "bonf")$p.value

library(tidyverse)
library(broom)
detach(package:plyr)

resPivot <- Genes %>% 
  drop_na() %>%
  pivot_longer(cols = -clust, names_to = "Features", values_to = "value") 
  
 res <- resPivot %>% 
  data.frame() %>%
  group_by(Features) %>% 
  tidyr::nest() %>%
  mutate(aov = map(data, ~summary(aov(value ~ clust, data = .x))[[1]][["Pr(>F)"]][1])) %>%
  select(-data) %>%
  ungroup() 

res$aov <- as.numeric(res$aov )

SelectedGenes <- res%>%
  top_n(-20,aov)

resPivotFilt <- resPivot %>%
  filter(Features %in% SelectedGenes$Features) 
  
  
  PlotInd1 <- resPivotFilt %>%
  group_by(clust,Features) %>%
  summarise(mean=mean(value), sd=sd(value))

PlotInd2 <-resPivotFilt %>%
  ungroup() %>%
  group_by(Features) %>%
  summarise(mean=mean(value), sd=sd(value)) %>%
  add_column(clust = "Mean")

PlotIndFinal <- rbind(PlotInd1, PlotInd2)
  
p <- ggplot(PlotIndFinal, aes(clust, mean, colour = clust)) + geom_point(position = "dodge")  + geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
   #geom_hline(aes(yintercept=mean, linetype="dashed", color = "red"))+
  theme_bw() + facet_wrap_paginate(Features ~. , scales = "free", ncol = 4, nrow = 5) 

pdf("GenesMine.pdf",15,10)
for(i in 1:n_pages(p)){
  p_save <-  p + 
    facet_wrap_paginate(Features ~ .,scales = "free", ncol = 4, nrow = 5, page = i)
  print(p_save)
}

dev.off()

  

```


```{r}

All <- Stanford %>%
  add_column(Ind_clus)

table(All$clust)
table(All$clust, All$GENDER)

Clinical2 <- Stanford %>%
  add_column(Ind_clus) %>%
  select(clust,ID, Study) %>%
  inner_join(Clinical %>% select(-c(CSV, missing))) %>%
  select(-c(ID,Study))

Multimorbidity <- Clinical2 %>%
  select(clust, Multimorbidity) %>%
  group_by(clust) %>%
  summarise(mean=mean(Multimorbidity), sd = sd(Multimorbidity))

res2 <- Clinical2 %>% 
  select(-Multimorbidity) %>%
  drop_na() %>%
  pivot_longer(-clust) %>%
  group_by(clust,name) %>%
  summarise(Prevalence = sum(value)/n()) %>%
  ungroup()

res2$name <- as.factor(res2$name)

pdf("DiseasesMine.pdf", 15, 24)
ggplot(res2, aes(clust, Prevalence, fill = clust, colour = clust )) + geom_col(position = "dodge") +
  facet_wrap(name ~., scales = "free") + theme_bw() + coord_flip()
dev.off()
```



```{r}
#PCA genes

Facto10 <- PCA(Montoya[,-c(1:8)],  quali.sup = c(3,4), scale.unit = TRUE, ncp = 10, graph = TRUE) 



```





```{r}
Clust <- Dataset %>%
  add_column(Ind_clus) 


pdf("Biplot.pdf",7,5)
fviz_pca_biplot(Facto20, 
                # Individuals
                geom.ind = "point",
                fill.ind = as.factor(Clust$clust), col.ind = "black",
                pointshape = 21, pointsize = 2,
                palette = "jco",
                addEllipses = TRUE,
                repel = TRUE,
                # Variables
                alpha.var ="contrib", col.var = "contrib",
                select.var = list(cos2 = 5) ,
                gradient.cols = "RdYlBu",
                
                legend.title = list(fill = "Clusters", color = "Contrib",
                                    alpha = "Contrib")
                )

dev.off()



```



```{r}

#run here - regression model 

Facto10 <- PCA(Dataset,  quali.sup = c(3,4), scale.unit = TRUE, ncp = 20, graph = TRUE) #maybe

DecisionTree <- data.frame(Facto10[["ind"]][["coord"]]) %>%
  add_column(BMI = Dataset$BMI)


library(rpart)

set.seed(1234)
output.tree <- rpart(BMI ~ ., data = DecisionTree, method="anova")

library(rpart.plot)
library(RColorBrewer)
library(rattle)
plot(output.tree)
text(output.tree,pretty=0)
summary(output.tree)
fancyRpartPlot(output.tree)

prediction_model <- predict(output.tree,DecisionTree,type="vector")

MAE <- function(actual,pred) {mean(abs(actual-pred))}
MAE(DecisionTree$BMI,prediction_model)

predicted.classes <- output.tree %>% predict(DecisionTree)
# Compute model accuracy rate on test data
MSE <- Metrics::rmse(as.numeric(DecisionTree$BMI), as.numeric(predicted.classes))
MSE


```

```{r}

FinalDataset2 <- FinalDataset  %>%
  select(unique(Select$name))

set.seed(1234)
output.tree <- rpart(BMI ~ ., data = FinalDataset2, method="anova")

plot(output.tree)
text(output.tree,pretty=0)
summary(output.tree)
fancyRpartPlot(output.tree)

prediction_model <- predict(output.tree,FinalDataset2,type="vector")

rss <- sum((prediction_model - FinalDataset2$BMI) ^ 2)  ## residual sum of squares
tss <- sum((FinalDataset2$BMI - mean(FinalDataset2$BMI)) ^ 2)  ## total sum of squares
rsq <- 1 - rss/tss #0.55
```



```{r}

#why are some variables missing?

Vars_Ind_Clust <- do.call(rbind, lapply(Individuals$desc.var[["quanti"]], as.data.frame)) %>%
  add_rownames() %>%
  separate(rowname, into =c("Cluster", "Feature"), sep = "\\.") 

MeanCat <- data.frame(Feature = Vars_Ind_Clust$Feature, Cluster ="Mean", Mean = Vars_Ind_Clust$`Overall mean`, Sd = Vars_Ind_Clust$`Overall sd`) %>%
  unique()

Vars_Ind_Clust2 <- Vars_Ind_Clust %>%
  select(Feature, Cluster, `Mean in category`,`sd in category`) %>%
  rename(Mean = `Mean in category`) %>%
  rename(Sd = `sd in category`) %>%
  rbind(.,MeanCat)
#geom_col(position = "dodge")

p <- ggplot(Vars_Ind_Clust2, aes(Cluster, Mean, colour = Cluster)) + geom_point(position = "dodge")  + geom_errorbar(aes(ymin=Mean-Sd, ymax=Mean+Sd), width=.2,
                 position=position_dodge(.9))+theme_bw() + facet_wrap_paginate(Feature ~. , scales = "free", ncol = 7, nrow = 7) 

pdf("MeanCluster.pdf",15,10)
for(i in 1:n_pages(p)){
  p_save <-  p + 
    facet_wrap_paginate(Feature ~ .,scales = "free", ncol = 7, nrow = 7, page = i)
  print(p_save)
}

dev.off()

```

```{r}
#quanti.sup = 6
Facto$quanti.sup

Vars <- fviz_pca_var( Facto, col.var = "contrib", title = "Correlation Plot of Variables")
corrplot()

#Investigate(Facto) #have to take the quali out 

Check_1 <- fviz_contrib(Facto, choice = "ind", axes = 1, top = 10)$data %>%
  top_n( 20, contrib)

Check_2 <- fviz_contrib(Facto, choice = "ind", axes = 2, top = 10)$data %>%
  top_n( 20, contrib)

#Also possibly divide into positive and negative subgroups 

plot.PCA(Facto, axes=c(1, 2), choix="ind", habillage=5)
dimdesc(Facto, axes=c(1,2)) #description of correlated variables with axis
plotellipses(Facto)

#check this specific individuals - in all plots
```



```{r}
FinalDatasetPlots <- FinalDataset %>%
  add_rownames() %>%
  mutate(Select = case_when(rowname %in% Check_1$name ~ "PCA1",
                            rowname %in% Check_2$name ~ "PCA2",
                            TRUE ~ "Standard")) %>%
   select(-c(ID, missing, CMV,rowname, Study,CSV)) %>%
  pivot_longer(-c(BMI,Select,GENDER))

library(ggforce)
pdf("FacetAll.pdf",15,10)
ggplot(FinalDatasetPlots, aes(BMI, value, colour = as.factor(Select ))) + geom_point() + 
  geom_smooth(method='lm', formula= y~x) +
 facet_wrap_paginate( name ~ ., scales = "free", ncol = 7, nrow = 7, page = 1) +
  theme_bw()

dev.off()


p <- ggplot(FinalDatasetPlots, aes(BMI, value, colour = as.factor(Select ))) + geom_point() + 
  geom_smooth(method='lm', formula= y~x) +
 facet_wrap_paginate( name ~ ., scales = "free", ncol = 7, nrow = 7) +
  theme_bw()

pdf("FacetAll.pdf",15,10)
for(i in 1:n_pages(p)){
  p_save <-  p + 
    facet_wrap_paginate(name ~ .,scales = "free", ncol = 7, nrow = 7, page = i)
  print(p_save)
}

dev.off()


#Separate study on patient 800

Strange <- FinalDataset[800,]
#SLVP015, ID 55
```


```{r}

Check_1 <- data.frame(contrib = Facto$ind$coord[,1]) %>%
  add_rownames() %>%
  mutate(Sign = ifelse(contrib >0, "Positive", "Negative"))

Check_2 <- data.frame(contrib = Facto$ind$coord[,2]) %>%
  add_rownames() %>%
  mutate(Sign = ifelse(contrib >0, "Positive", "Negative"))

a <- FinalDataset[,c(1:10)] %>%
  add_rownames() %>%
mutate(Select = ifelse(rowname %in% filter(Check_1, Sign == "Positive")$rowname & rowname %in% filter(Check_2, Sign == "Positive")$rowname,  "PCA1-Pos/PCA2-Pos", "No"))

FinalDatasetPlots2 <- FinalDataset %>%
  add_rownames() %>%
  mutate(Select = case_when(rowname %in% intersect(filter(Check_1, Sign == "Positive")$rowname, filter(Check_2, Sign == "Positive")$rowname) ~ "PCA1-Pos/PCA2-Pos",
                            rowname %in% intersect(filter(Check_1, Sign == "Negative")$rowname, filter(Check_2, Sign == "Negative")$rowname) ~ "PCA1-Neg/PCA2-Neg",
                            rowname %in% intersect(filter(Check_1, Sign == "Positive")$rowname, filter(Check_2, Sign == "Negative")$rowname) ~ "PCA1-Pos/PCA2-Neg",
                            rowname %in% intersect(filter(Check_1, Sign == "Negative")$rowname, filter(Check_2, Sign == "Positive")$rowname) ~ "PCA1-Neg/PCA2-Pos")) %>%
   select(-c(ID, missing, CMV,rowname, Study,CSV)) %>%
  pivot_longer(-c(BMI,Select,GENDER))



p <- ggplot(FinalDatasetPlots2, aes(BMI, value, colour = as.factor(Select ))) + geom_point(alpha = 0.4) + 
  geom_smooth(method='lm', formula= y~x) +
 facet_wrap_paginate( name ~ ., scales = "free", ncol = 7, nrow = 7) +
  theme_bw()

pdf("Subgroup.pdf",15,10)

for(i in 1:n_pages(p)){
  p_save <-  p + 
    facet_wrap_paginate(name ~ .,scales = "free", ncol = 7, nrow = 7, page = i)
  print(p_save)
}

dev.off()


```



```{r}
fviz_eig(Facto, addlabels = TRUE, ylim = c(0, 50))

fviz_pca_var(Facto, col.var = "contrib", #cos2
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), 
             repel = TRUE # Avoid text overlapping
             )

One <- fviz_contrib(Facto, choice = "var", axes = 1, top = 10)
Two <- fviz_contrib(Facto, choice = "var", axes = 2, top = 10)

score <- as_tibble(factoextra::get_pca_ind(Facto)$coord)$Dim.1 #extract individual scores


  
```